"""
[3c_gapfill_3] Call the internal API to read and fill each gap year's data from later reports.
    Step 3 | run by hand | needs the selected PDF pages already generated by Step 1, and the internal API

Purpose
    For each gap year T in Step 2's list, try candidate reports in order, stopping at the first hit:
        the report published in year T+2 (if there is more than one that year, try the latest first,
        then earlier ones)
        -> the report published in year T+3 (again, latest first)
    Read the column for year T in these reports' DSA decomposition tables. Only actual / historical
    columns are accepted; preliminary / estimate / projection are never accepted. If T+3 also fails to
    yield the year, the gap is marked unresolved and no further years (T+4, ...) are tried.

    This step does not read the original staff report PDF again, does not re-locate the DSA table, and
    does not recompress the PDF: it uses directly the selected PDF pages already produced by Step 1
    (the exact PDF that was sent to the API at the time).

Input (paths set in the CONFIG below)
    TARGETS_CSV, SKIP_CSV     the two CSVs from Step 2
    SELECTED_PDF_DIRS         Step 1's selected_pdf_pages folders (several batches can be listed; earlier
                              ones take priority). The candidate reports are exactly the reports that
                              already have a selected PDF in one of these folders.
                              A selected PDF's file name is <country>_<date>[_CR number]<any suffix>.pdf;
                              it is matched to a report by the leading country_date(_CR number) part, and
                              the suffix can be anything (e.g. _pages_5_8, _page_6_table_crop_fallback).
                              The json_output folder next to each of these folders (or the folder above
                              it) should hold Step 1's <report>_timing.json, used to determine which PDF
                              was actually sent to the API at the time, the page mapping, and the
                              rendering method.
    GAPFILL_PROMPT_FILE       gapfill_extraction_prompt_v2.txt
    STEP1_SCRIPT, ENV_FILE    the Step 1 script (reused for its API auth / retry / call functions) and .env
    PANEL_CSV (optional)      Step 1's panel_structure, used to build the filled-in panel

Output (OUTPUT_DIR = output/gapfill/<batch>_<STAMP>/)
    reports/<report>_gapfill.json       one per report that was called: the model's raw answer and the
                                        validation result for each target year (also the resume cache)
    gapfill_resolution_<STAMP>.csv      the final result for each gap year (resolved / resolved_with_warning /
                                        unresolved ...) and its source report
    gapfill_attempts_<STAMP>.csv        a record of each attempt: which report, what status, failure reason
    gapfill_values_long_<STAMP>.csv     the extracted values, long format (including child-item level)
    gapfill_values_wide_<STAMP>.csv     the extracted values, wide format (the six top-level variables)
    panel_structure_filled_<STAMP>.csv  the panel with its GAP rows filled in (needs PANEL_CSV)
    RUN_SUMMARY_<STAMP>.json            a summary of the results

Core steps
    1. Read targets and skip, scan the selected PDFs in SELECTED_PDF_DIRS, and build the candidate-report
       order for each gap year (T+2 -> T+3, skipping reports listed in skip).
    2. Process in waves: in each wave, the gap years that currently land on the same report are merged
       into a single API call.
    3. For each report: find its selected PDF (preferring the one recorded in timing.json as actually
       sent at the time; when there is no timing.json, by priority direct page selection > compressed
       image > table crop > full-page compressed image) -> call the API with prompt v2, with the target
       years in the request. A report whose selected PDF cannot be found is recorded as
       selected_pdf_not_found and the next report is tried instead.
    4. Actual validation: the column status must be actual / historical; the header text must not contain
       Prel. / Est. / Proj.; the status for that year in the model's own list of year columns must be
       compliant; it must not be the case that an earlier year is projection while the target year is
       actual. A second, independent header check is only sent when the model's own list of year columns
       is missing this year, or contradicts its own answer. Failing validation -> the next report is tried.
    5. Each report's result is cached in reports/*.json: resuming after an interruption does not re-call
       the API; a report whose call errored is not cached, so a rerun retries it automatically. A selected
       PDF that, together with this step's prompt, exceeds the gateway's request-body limit is recorded as
       pdf_too_large and the next report is tried.
    6. Once everything is done, the summary files above are written.

Usage (set up CONFIG first)
    python 3c_gapfill_3_run_api.py --dry-run                     list the planned calls and check that every
                                                                  selected PDF can be found; no API call
                                                                  (do this first)
    python 3c_gapfill_3_run_api.py --limit-gaps 5                run only the first 5 gap years (a small
                                                                  pilot run, to check the output JSON)
    python 3c_gapfill_3_run_api.py --countries "Angola,Chile"    run only the given countries
    python 3c_gapfill_3_run_api.py                               full run
    python 3c_gapfill_3_run_api.py --collect-only                no API call; rebuild the summary files
                                                                  from the already-saved JSON

gapfill_lib_core.py must be in the same folder (imported by this script; not meant to be run on its own).
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
import time
from pathlib import Path, PureWindowsPath
from typing import Any, Dict, List, Optional

import pandas as pd

def _here() -> Path:
    """Folder holding the gapfill scripts. Uses __file__ when the file is run
    normally; in an IPython / PyCharm console (no __file__) it looks for the
    folder that contains gapfill_lib_core.py, starting from the working folder."""
    try:
        return Path(__file__).resolve().parent
    except NameError:
        cwd = Path.cwd()
        for cand in (cwd, cwd / "code", cwd.parent / "code", cwd.parent):
            if (cand / "gapfill_lib_core.py").exists():
                return cand
        return cwd

HERE = _here()
sys.path.insert(0, str(HERE))
try:
    import gapfill_lib_core as core  # noqa: E402
except ModuleNotFoundError as exc:
    raise ModuleNotFoundError(
        f"{exc}. gapfill_lib_core.py must be in the same folder as this script; "
        f"looked in {HERE}. In a console, first run  %cd <path to the code folder>  or set HERE by hand."
    ) from exc

# =============================================================== CONFIG (edit)
BASE_DIR = Path(r"C:\Users\xli7\OneDrive - International Monetary Fund (PRD)\Shelley_My Projects\SFA")

# Step 1's "selected_pdf_pages" folders, one per batch. The first folder that holds a report's
# selected PDF wins, so list re-run folders (e.g. .../2016-2020/rerun_20260910/selected_pdf_pages)
# BEFORE the original ones. The Step 1 "<report>_timing.json" files are expected in the folder
# above each of these (or in a "json_output" folder next to it).
SELECTED_PDF_DIRS: List[Path] = [
    BASE_DIR / "output" / "2011-2015" / "round1_20260921_run1" / "selected_pdf_pages",
    BASE_DIR / "output" / "2016-2020" / "round2_20260921_run1" / "selected_pdf_pages",
    BASE_DIR / "output" / "2016-2020" / "round1_20260921_run1" / "selected_pdf_pages",
    BASE_DIR / "output" / "2021-2026" / "round1_20260921_run1" / "selected_pdf_pages",
]

STEP1_SCRIPT = HERE / "1a_two_step_selected_pdf_inline_base64_cropfallback_summary_v7_header_aware_crop_effort.py"
# 1a (not 2a/round2's pipeline) on purpose: gap-fill only needs call_pdf_json / make_api_session /
# add_table_crop_header_instruction, identical in both; 2a's extra accuracy is specifically about
# *choosing* last_actual_year, which gap-fill never does (the target year is already given).
GAPFILL_PROMPT_FILE = BASE_DIR / "gapfill_extraction_prompt_v2.txt"
ENV_FILE = BASE_DIR / ".env"

STAMP = "20260920_v2"  # must match the STAMP of 3a / 3b
CHECK_DIR = BASE_DIR / "output" / "2016-2020" / "gap_year_check"
TARGETS_CSV = CHECK_DIR / f"gapfill_targets_{STAMP}.csv"
SKIP_CSV = CHECK_DIR / f"gapfill_skip_reports_{STAMP}.csv"
PANEL_CSV: Optional[Path] = CHECK_DIR / f"panel_structure_country_year_{STAMP}.csv"  # None = do not build the filled panel
OUTPUT_DIR = BASE_DIR / "output" / "gapfill" / f"2016-2020_{STAMP}"

MAX_WORKERS = 4
# ==============================================================================

SIZE_PHRASES = [
    "maximum allowed size", "request entity too large", "error 413",
    "above the configured base64-safe limit", "too close to or above the 1 mb gateway limit",
]

# A selected PDF is named "<report stem><any suffix>.pdf". The report stem is "<country>_<YYYY-MM-DD>",
# optionally followed by a Country Report number ("_CR2019-283"). Whatever comes after (_pages_5_8,
# _page_6_table_crop_fallback, or anything else) is only used to guess how the PDF was made.
_STEM_RE = re.compile(r"^(?P<stem>.+?_\d{4}-\d{2}-\d{2}(?:_CR\d{4}-\d+)?)(?P<suffix>_.*)?\.pdf$", re.IGNORECASE)
# Best fidelity first (used only when there is no timing.json to say which file was sent).
_METHOD_ORDER = [
    "selected_pdf_direct", "selected_pdf_image_compressed",
    "pymupdf_pillow_table_crop_fallback", "pymupdf_pillow_visual_fallback",
]


def build_gapfill_audit_prompt() -> str:
    return (
        "INDEPENDENT HEADER AUDIT ONLY\n\n"
        "Inspect the complete multi-level column header of the qualifying PUBLIC DSA decomposition table in the "
        "attached PDF. Do not extract any rows or values. Do not assume any earlier answer is right or wrong.\n"
        "List EVERY visible year column from left to right. Status vocabulary: actual, historical, preliminary, "
        "estimate, projection, unknown. A merged span such as 2002-2010 is one column with its own label. A "
        "two-part label such as 2015/16 stands for its end year. Use the group headings, separators, spacing and "
        "table notes; if the status cannot be established use unknown.\n"
        "Return ONLY this JSON object:\n"
        '{"column_header_audit": {"columns": [{"position": 1, "year_label": "", "group_label": null, '
        '"status": "actual", "status_basis": ""}]}, "issues": []}\n'
    )


def load_step1():
    spec = importlib.util.spec_from_file_location("step1_module", str(STEP1_SCRIPT))
    mod = importlib.util.module_from_spec(spec)
    sys.modules["step1_module"] = mod
    spec.loader.exec_module(mod)
    mod.ENV_FILE = ENV_FILE
    return mod


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str), encoding="utf-8")


# ------------------------------------------------------- selected PDF lookup
def parse_selected_name(name: str):
    """(report stem, method) for a selected-PDF file name, else None if it has no <country>_<date> part."""
    m = _STEM_RE.match(name)
    if not m:
        return None
    suffix = (m.group("suffix") or "").lower()
    if "crop" in suffix:
        method = "pymupdf_pillow_table_crop_fallback"
    elif "vision" in suffix or "visual" in suffix:
        method = "pymupdf_pillow_visual_fallback"
    elif "compress" in suffix:
        method = "selected_pdf_image_compressed"
    else:
        method = "selected_pdf_direct"
    return m.group("stem"), method


def index_selected_pdfs(dirs: List[Path]) -> Dict[str, List[Dict[str, Any]]]:
    """stem -> selected PDFs found in `dirs` (each with its folder rank and method rank)."""
    idx: Dict[str, List[Dict[str, Any]]] = {}
    for dir_rank, d in enumerate(dirs):
        if not d.exists():
            print(f"  WARNING: selected-PDF folder not found: {d}")
            continue
        ignored = []
        for p in sorted(d.glob("*.pdf")):
            parsed = parse_selected_name(p.name)
            if parsed:
                stem, method = parsed
                idx.setdefault(stem, []).append(
                    {"path": p, "method": method, "dir": d, "dir_rank": dir_rank,
                     "method_rank": _METHOD_ORDER.index(method)}
                )
            else:
                ignored.append(p.name)
        if ignored:
            print(f"  WARNING: {len(ignored)} PDF(s) in {d} have no <country>_<YYYY-MM-DD> in the name and are ignored, e.g. {ignored[:3]}")
    return idx


def read_timing(selected_dir: Path, stem: str) -> Optional[Dict[str, Any]]:
    """Step 1's <report>_timing.json: in "json_output" next to the selected folder (current layout),
    or directly in the folder above it (older layout)."""
    for p in (selected_dir.parent / "json_output" / f"{stem}_timing.json", selected_dir.parent / f"{stem}_timing.json"):
        if p.exists():
            try:
                return json.loads(p.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                return None
    return None


def resolve_selected_pdf(stem: str, idx: Dict[str, List[Dict[str, Any]]]) -> Optional[Dict[str, Any]]:
    """
    The selected PDF to send for one report.
    1. The file Step 1's timing.json says was sent to the API (also gives the page mapping,
       rendering method and crop box). Folders are tried in SELECTED_PDF_DIRS order.
    2. Otherwise the best-fidelity selected PDF by file name (no page mapping available).
    """
    found = idx.get(stem, [])
    if not found:
        return None
    for dir_rank in sorted({f["dir_rank"] for f in found}):
        same_dir = [f for f in found if f["dir_rank"] == dir_rank]
        timing = read_timing(same_dir[0]["dir"], stem)
        sent = PureWindowsPath(str(timing.get("pdf_sent_to_api") or "")).name if timing else ""
        for f in same_dir:
            if sent and f["path"].name == sent:
                return {
                    "path": f["path"], "source": "timing", "method": timing.get("extraction_method") or f["method"],
                    "pages": timing.get("selected_original_pages"), "dpi": timing.get("vision_fallback_dpi"),
                    "quality": timing.get("vision_fallback_jpeg_quality"), "box": timing.get("table_crop_box_points"),
                }
    best = min(found, key=lambda f: (f["dir_rank"], f["method_rank"], f["path"].name))
    return {"path": best["path"], "source": "filename", "method": best["method"],
            "pages": None, "dpi": None, "quality": None, "box": None}


# ---------------------------------------------------------------- cache utils
def report_json_path(stem: str) -> Path:
    return OUTPUT_DIR / "reports" / f"{stem}_gapfill.json"


def read_cache(stem: str) -> Dict[str, Any]:
    p = report_json_path(stem)
    if p.exists():
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return {}
    return {}


def cached_outcomes(stem: str, years: List[int]) -> Dict[int, Dict[str, Any]]:
    per = read_cache(stem).get("per_target", {})
    out = {}
    for y in years:
        o = per.get(str(y))
        if o and o.get("status") not in core.STOP_STATUSES:
            out[y] = o
    return out


def cache_only_process(report: Dict[str, Any], years: List[int]) -> Dict[int, Dict[str, Any]]:
    stem = Path(report["pdf_file_name"]).stem
    got = cached_outcomes(stem, years)
    return {y: got.get(y, {"status": "not_run", "errors": [], "warnings": []}) for y in years}


# ------------------------------------------------------------------ processor
class ReportProcessor:
    def __init__(self, s1, url, token_manager, model, prompt, selected_index):
        self.s1, self.url, self.tm, self.model = s1, url, token_manager, model
        self.prompt, self.selected_index = prompt, selected_index

    def user_text(self, sel: Dict[str, Any], stem: str, country: str, report_date: str, years: List[int]) -> str:
        if sel["pages"]:
            mapping = "\n".join(
                f"Selected PDF page {i} = original physical PDF page {p}" for i, p in enumerate(sel["pages"], start=1)
            )
        else:
            mapping = "not available (leave page_pdf null)"
        text = (
            f"Original PDF file: {stem}.pdf\n"
            f"Selected PDF file: {sel['path'].name}\n"
            f"Input rendering method: {sel['method']}\n"
            f"Rendering DPI: {sel['dpi']}\n"
            f"JPEG quality: {sel['quality']}\n"
            f"Table crop box: {sel['box']}\n\n"
            f"ORIGINAL PHYSICAL PAGE MAPPING:\n{mapping}\n\n"
            "GAP-FILL REQUEST:\n"
            f"Country: {country}\n"
            f"Staff report file: {stem}.pdf (report date {report_date})\n"
            f"TARGET YEARS (extract each one, from ACTUAL or HISTORICAL columns only): {json.dumps(years)}\n"
        )
        return self.s1.add_table_crop_header_instruction(text, sel["method"])

    def __call__(self, report: Dict[str, Any], years: List[int]) -> Dict[int, Dict[str, Any]]:
        started = time.perf_counter()
        stem = Path(report["pdf_file_name"]).stem
        cached = cached_outcomes(stem, years)
        todo = [y for y in years if y not in cached]
        if not todo:
            return cached

        sel = resolve_selected_pdf(stem, self.selected_index)
        if sel is None:
            return {**cached, **{y: {"status": "selected_pdf_not_found", "errors": ["no selected PDF found for this report"], "warnings": []} for y in todo}}

        prev = read_cache(stem)
        record: Dict[str, Any] = {
            "pdf_file_name": report["pdf_file_name"], "country": report["country"], "report_date": report["date"],
            "selected_pdf": str(sel["path"]), "selected_pdf_source": sel["source"],
            "extraction_method": sel["method"], "selected_original_pages": sel["pages"],
            "per_target": prev.get("per_target", {}), "calls": prev.get("calls", []),
        }
        outcomes: Dict[int, Dict[str, Any]] = dict(cached)
        try:
            outcomes.update(self._extract(sel, stem, report, todo, record))
        except Exception as exc:
            size_related = any(p in str(exc).lower() for p in SIZE_PHRASES)
            status = "pdf_too_large" if size_related else "api_error"
            for y in todo:
                outcomes[y] = {"status": status, "errors": [f"{type(exc).__name__}: {exc}"], "warnings": []}

        for y, o in outcomes.items():
            record["per_target"][str(y)] = o
        record["timing_seconds"] = round(time.perf_counter() - started, 2)
        write_json(report_json_path(stem), record)
        return outcomes

    def _extract(self, sel, stem, report, years, record) -> Dict[int, Dict[str, Any]]:
        s1 = self.s1
        user_text = self.user_text(sel, stem, report["country"], report["date"], years)
        model_out = s1.call_pdf_json(self.url, self.tm, self.model, self.prompt, user_text, sel["path"])
        record["calls"].append({"target_years": years, "model_output": model_out})

        if not model_out.get("table_found"):
            reason = model_out.get("failure_reason")
            return {y: {"status": "no_dsa_table", "errors": [f"model: table_found=false ({reason})"], "warnings": []} for y in years}

        source = model_out.get("source") or {}
        by_year: Dict[int, Dict[str, Any]] = {}
        for t in model_out.get("targets") or []:
            try:
                by_year[int(t.get("target_year"))] = t
            except (TypeError, ValueError):
                continue

        outcomes: Dict[int, Dict[str, Any]] = {}
        for y in years:
            t = by_year.get(y)
            if t is None:
                outcomes[y] = {"status": "not_extracted", "errors": ["model returned no entry for this year"], "warnings": []}
                continue
            t["target_year"] = y
            status, errors, warnings = core.validate_target(t, source)
            err_msgs = [m for _c, m in errors]
            if status == "needs_independent_audit":
                audit = s1.call_pdf_json(self.url, self.tm, self.model, build_gapfill_audit_prompt(), user_text, sel["path"])
                record.setdefault("independent_audits", {})[str(y)] = audit
                ok, msg = core.audit_confirms(audit, y)
                if ok:
                    status = "resolved_with_warning"
                    warnings = warnings + err_msgs + [msg]
                    err_msgs = []
                else:
                    status = "rejected_not_actual"
                    err_msgs = err_msgs + [msg]
            outcomes[y] = {
                "status": status, "errors": err_msgs, "warnings": warnings,
                "column_status": t.get("column_status"),
                "column_header_verbatim": t.get("column_header_verbatim"),
                "not_extractable_reason": t.get("not_extractable_reason"),
                "decomposition": t.get("decomposition") if status in core.RESOLVED else None,
                "unmapped_rows": t.get("unmapped_rows") if status in core.RESOLVED else None,
                "notes": t.get("notes"),
                "meta": {
                    "framework": source.get("framework"), "units_verbatim": source.get("units_verbatim"),
                    "table_number": source.get("table_number"), "page_pdf": source.get("page_pdf"),
                    "confidence": source.get("confidence"), "extraction_method": sel["method"],
                },
            }
        return outcomes


# ------------------------------------------------------------------------ main
def reports_from_selected(idx: Dict[str, List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
    """One report record (country, date, year from the file name) per report that has a selected PDF."""
    reports = []
    for stem in sorted(idx):
        rec = core.parse_report_file(Path(stem + ".pdf"))
        if rec:
            reports.append(rec)
    return reports


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="list planned calls and check selected PDFs; no API")
    ap.add_argument("--collect-only", action="store_true", help="rebuild outputs from saved JSONs; no API")
    ap.add_argument("--limit-gaps", type=int, default=None, help="only the first N gap years (pilot)")
    ap.add_argument("--countries", type=str, default=None, help="comma-separated country names to run")
    args, _ = ap.parse_known_args()  # tolerant of extra args injected by IPython/Spyder

    targets = pd.read_csv(TARGETS_CSV)
    run = targets.copy()
    if args.countries:
        wanted = {c.strip() for c in args.countries.split(",")}
        run = run[run["country"].isin(wanted)]
    run = run.sort_values(["country", "gap_year"])
    if args.limit_gaps:
        run = run.head(args.limit_gaps)
    skip = set(pd.read_csv(SKIP_CSV)["pdf_file_name"]) if SKIP_CSV.exists() else set()

    print(f"Gap years selected: {len(run)} of {len(targets)}")
    selected_index = index_selected_pdfs(SELECTED_PDF_DIRS)
    reports = reports_from_selected(selected_index)
    idx = core.index_by_country_year(reports)
    print(f"Reports with a selected PDF: {len(reports)} in {len(SELECTED_PDF_DIRS)} folder(s); reports never used as a source: {len(skip)}")

    def candidates_fn(country: str, year: int):
        return core.build_candidates(country, year, idx, skip)

    gap_items = run[["gap_id", "country", "gap_year"]].to_dict("records")

    if args.dry_run:
        first_wave, none = set(), 0
        for g in gap_items:
            c = candidates_fn(g["country"], int(g["gap_year"]))
            if not c:
                none += 1
            else:
                first_wave.add(c[0]["pdf_file_name"])
            print(f"  {g['gap_id']} {g['country']} {g['gap_year']}: " + (", ".join(f"[T+{x['offset']}] {x['pdf_file_name']}" for x in c[:4]) or "NO CANDIDATE REPORT"))
        by_timing = sum(1 for n in first_wave if (resolve_selected_pdf(Path(n).stem, selected_index) or {}).get("source") == "timing")
        print(f"\nDry run: first wave = {len(first_wave)} API report call(s); gap years with no candidate report = {none}")
        print(f"Selected PDF identified from timing.json for {by_timing} of the {len(first_wave)} first-wave reports (the rest fall back to file-name priority, without page mapping)")
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    if args.collect_only:
        process_fn = cache_only_process
        workers = 1
    else:
        s1 = load_step1()
        prompt = GAPFILL_PROMPT_FILE.read_text(encoding="utf-8")
        url, tm, model = s1.make_api_session()
        print(f"Model: {model}")
        process_fn = ReportProcessor(s1, url, tm, model, prompt, selected_index)
        workers = MAX_WORKERS

    state = core.run_cascade(gap_items, candidates_fn, process_fn, max_workers=workers)
    paths = core.write_outputs(state, targets, OUTPUT_DIR, STAMP, PANEL_CSV)

    counts: Dict[str, int] = {}
    for st in state:
        counts[st["final_status"]] = counts.get(st["final_status"], 0) + 1
    summary = {"gap_years": len(state), "final_status_counts": counts,
               "runtime_seconds": round(time.perf_counter() - started, 1),
               "outputs": {k: str(v) for k, v in paths.items()}}
    write_json(OUTPUT_DIR / f"RUN_SUMMARY_{STAMP}.json", summary)
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
